Snarfing overhaul to make it guile-version-independent now compiles and runs under guile-1.5.6 some issues remain - bound? in cmds.scm for example.

diff --git a/src/scwm-snarf b/src/scwm-snarf
--- a/src/scwm-snarf
+++ b/src/scwm-snarf
@@ -1,7 +1,9 @@
 #!/bin/sh -
-# scwm-snarf
+# scwm-snarf 
 # (C) 1999 Ken Pizzini and Greg J. Badros
-# Handle snarfs with embedded %/%/ separating the arglist of procedures
+# 	contents of guile-1.4's guile-snarf merged in by Steve Tell
+#
+## Handle snarfs with embedded %/%/ separating the arglist of procedures
 # from the rest.
 # See scwm-snarf.h for what expands SCWM_PROC macros to what we process here.
 # We need to do a couple of regexp search and replaces:
@@ -10,7 +12,20 @@
 # s/"(/"'(/g  # add the Scheme quote to the list -- tricky shell quoting below
 # AND we need these to only happen *after* the %/%/ marker on the input lines
 # so we use two sed's to do it.
-guile-snarf "$@" | \
+
+#!/bin/sh
+# Extract the initialization actions for builtin things.
+
+temp="/tmp/snarf.$$"
+trap "rm -f $temp" 0 1 2 15
+
+## Let the user override the preprocessor autoconf found.
+test -n "${CPP+set}" || CPP="gcc -E"
+
+## We must use a temporary file here, instead of a pipe, because we
+## need to know if CPP exits with a non-zero status.
+${CPP} -DSCM_MAGIC_SNARFER "$@" > ${temp} || exit $?
+< ${temp} grep "^ *SCM__I" | sed -e "s/^ *SCM__I//" -e 's/SCM__D.*$//g' | \
 sed 's@%/%/@\
 @
        /\n/!b
@@ -21,3 +36,8 @@ sed 's@%/%/@\
        x
        G
        s/\n.*\n//' 
+
+## Apparently, AIX's preprocessor is unhappy if you try to #include an
+## empty file.
+echo
+
